services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ada
      - MONGO_INITDB_ROOT_PASSWORD=lovelace
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=ada
      - ME_CONFIG_MONGODB_ADMINPASSWORD=lovelace
      - ME_CONFIG_MONGODB_SERVER=mongodb
